[package]
name = "actionkv"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
crc = "3.4.0"
serde = {version="1.0.229", features=["derive"]}
serde_json = {version = "1.0.151"}

[lib]
name = "libactionkv"
path = "src/lib.rs"

[[bin]]
name = "akv_mem"
path = "src/akv_mem.rs"

[[bin]]
name = "test_endian"
path = "src/read_write_endian.rs"

[[bin]]
name = "parity_bit"
path = "src/parity_bit.rs"
